### ISSUE TITLE
คิด Theme, คิดหัวข้อ

### ISSUE THREAD

**Issue by pruk17** [pruk17/ScratchProject-1#1]
ช่วยกันเสนอ theme เกม

**Comment by OrneryCash** [comment]
**ได้หัวข้อ: รับน้องขึ้นดอย**

**Comment by OrneryCash** [comment]
**ได้หัวข้อ: รับน้องขึ้นดอย**
**ชื่อเกม: ร้อยแรงใจ ขึ้นดอยสุเทพ**
