### ISSUE TITLE
สร้างหน้าต่างเริ่มต้นเกม

### ISSUE THREAD

**Issue by OrneryCash** [pruk17/ScratchProject-1#4]

**Comment by OrneryCash** [comment]
[ร้อยแรงใจ ขึ้นดอยสุเทพ v01.zip](https://github.com/pruk17/ScratchProject-1/files/12505191/v01.zip)

**Comment by pruk17** [comment]
พื้นหลังหน้า Start game ตอนนี้
![วิ่งขึ้นดอย](https://github.com/pruk17/ScratchProject-1/assets/141806587/64814c42-04cb-43ee-8529-e40a15be411b)

**Comment by pruk17** [comment]
พื้นหลังที่ใช้วิ่ง
![พื้นหลังวิ่ง1](https://github.com/pruk17/ScratchProject-1/assets/141806587/74028a09-c529-4f3e-b134-afbc064441d0)
![พื้นหลังวิ่ง2](https://github.com/pruk17/ScratchProject-1/assets/141806587/c7f678eb-90bc-429f-bbd7-3894f2077db2)
