### ISSUE TITLE
design และวาดรูปตัวละคร

### ISSUE THREAD

**Issue by OrneryCash** [pruk17/ScratchProject-1#6]

**Comment by OrneryCash** [comment]
[character.zip](https://github.com/pruk17/ScratchProject-1/files/12506096/character.zip)

**Comment by pruk17** [comment]
ผู้ชาย
![ชาย ขยับข้าง](https://github.com/pruk17/ScratchProject-1/assets/141806587/d9eb7a1f-15cf-44da-a80f-61e8880cea69)
![ชาย วิ่ง](https://github.com/pruk17/ScratchProject-1/assets/141806587/48d136de-dc6b-4d9b-aedc-8ecc75048922)
![ชาย กระโดด](https://github.com/pruk17/ScratchProject-1/assets/141806587/4862c61e-210b-4912-a18c-2381407796d6)
ผู้หญิง
![หญิง กระโดด](https://github.com/pruk17/ScratchProject-1/assets/141806587/ef96ae4b-25c2-40c7-8e0a-0c827609fd75)
![หญิง ขยับข้าง](https://github.com/pruk17/ScratchProject-1/assets/141806587/95387a16-1d72-44f1-be7d-b68b1efbc0a0)
![หญิง วิ่ง](https://github.com/pruk17/ScratchProject-1/assets/141806587/309b28db-dabb-4e9b-b53c-9250927e18b7)
